<a href="https://colab.research.google.com/github/zza0818/py-11/blob/master/Py11_Summary_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###라이브러리-overview

-라이브러리 이름을 바로 임포트하는 방법
-해당 라이브러리의 풀네임을 이용하여 필요한 값 호출 가능

In [0]:
import numpy

A = numpy.array([1,2])

print("A == ", A, ", type ==", type(A))

A ==  [1 2] , type == <class 'numpy.ndarray'>


-가장 일반적인 방법 

-라이브러리에 별명을 지정하는 방식

-

In [0]:
import numpy as np

A = np.array([1,2])

print("A ==", A, ", type ==", type(A))

A == [1 2] , type == <class 'numpy.ndarray'>


-해당 numpy의 이름을 쓰지 않고 바로 exp 사용 가능

-

In [0]:
from numpy import exp 

result = exp(1)

print("result ==", result, ", type ==", type(result))

result == 2.718281828459045 , type == <class 'numpy.float64'>


-필요한 라이브러리에 모든걸 사용한다는 의미 

-라이브러리 이름 사용 x

In [0]:
from numpy import *

result = exp(1) + log(1.7) + sqrt(2)

print("result ==", result, ", type ==", type(result))

result == 4.663123641894311 , type == <class 'numpy.float64'>


##numpy

-vector/matrix생성

-행렬 곱 (dot product)

-index/ slice/ iterator

-concatenate

-useful function (loadtxt(), rand(), argmax(), ...)

###numpy

=> numpy는 머신러닝 코드 개발 할 경우 자주 사용되는 벡터, 행렬 등을 표현하고 연산할 때 반드시 필요한 라이브러리 

###numpy vs list 

=> 머신러닝에서 숫자, 사람, 동물 등의 인식을 하기 위해서는 이미지(image)데이터를 행렬(matrix)로 변환 하는 것이 중요함 

=> 행렬(matrix)을 나타네기 위해서는 리스트(list)를 사용할 수도 있지만, 행렬 연산이 직관적이지 않고 오류 가능성이 높기 때문에, 행렬 연산을 위해서는 numpy 사용이 필수임

In [0]:
import numpy as np 

In [0]:
#리스트로 행렬 표현 

A = [ [1,0], [0,1] ]
B = [ [1,1], [1,1] ] 

A + B #행렬 연산 

[[1, 0], [0, 1], [1, 1], [1, 1]]

In [0]:
# numpy matrix,직관적임

A = np.array([ [1,0], [0,1] ])
B = np.array([ [1,1], [1,1] ])

A + B

array([[2, 1],
       [1, 2]])

###라이브러리 - numpy vector (1차원 배열)

-벡터(vector)생성 

=>vector는 np.array([...])를 사용하여 생성함 (import numpy as np)

=> 머신러닝 코드 구현 시, 연산을 위해서 vector,matrix 등의 형상(shape),차원(dimension)을 확인하는 것이 필요함 

- 벡터(vector)산술 연산

=> vector 간 산술연산(+,-,×,/)은 벡터의 각각의 원소에 대해서 행해짐

In [0]:
A = np.array([1,2,3]) 
B = np.array([4,5,6])

#vector A, B 출력
print("A ==", A, ", B ==", B)

#vector A, B 형상 출력 => shape 
print("A.shape ==", A.shape, ", B.shape ==", B.shape)

#vector A,B 차원 출력 => ndim
print("A.ndim ==", A.ndim, ", B.dim ==", B.ndim)

A == [1 2 3] , B == [4 5 6]
A.shape == (3,) , B.shape == (3,)
A.ndim == 1 , B.dim == 1


In [0]:
#vector 산술 연산 

print("A + B ==", A+B)
print("A - B ==", A-B)
print("A * B ==", A*B)
print("A / B ==", A/B)

A + B == [5 7 9]
A - B == [-3 -3 -3]
A * B == [ 4 10 18]
A / B == [0.25 0.4  0.5 ]


###라이브러리 - numpy matrix(행렬)

- 행렬(matrix) 생성 

=> matrix는 vector와 마찬가지로 np.array([  [...], [...], ...]) 를 사용하여 생성함  (import numpy as np)

In [0]:
A = np.array([ [1,2,3], [4,5,6] ])
B = np.array([ [-1,-2,-3], [-4,-5,-6] ])

#matrix A,B 형상 출력 => shape
print("A.shape ==", A.shape, ", B.shpae ==", B.shape)

# matrix A,B 차원 출력 => ndim 
print ("A.ndim ==", A.ndim, ", B.ndim ==", B.ndim)
              

A.shape == (2, 3) , B.shpae == (2, 3)
A.ndim == 2 , B.ndim == 2


- 형 변환(reshape)

=> vector를 matrix로  변경라거나 matrix를 다른 형상의 matrix로 변경하기 위해서는 reshape()사용하여 행렬의 shape을  변경하여야 함 

In [0]:
#vector 생성

C = np.array([1,2,3])

#vector C형상 출력 => shape
print("C.shape ==", C.shape)

#vector를 (1,3) 행렬로 형 변환
C = C.reshape(1,3)

print("C.shape ==", C.shape)

C.shape == (3,)
C.shape == (1, 3)


###라이브러리 -numpy 행렬 곱 (dot product) 1 

-행렬 곱 (dot product)

=> A 행렬과 B 행렬의 행렬 곱 (dot product)는 np.dot(A,B) 나타내며,행렬 A의 열 벡터와 B 행렬의 행 벡터가 같아야 함. 민약 같지 않다면 reshape 또는 전치행렬(transpose)등을 사용하여 형 변환을 한 후에 행렬 곱 실행해야 함

In [0]:
A = np.array([ [1,2,3],[4,5,6] ]) #2×3 행렬
B = np.array([ [-1,-2], [-3,-4],[-5,-6] ]) #3×2행렬

#(2×3) dot product (3x2) == (2×2)행렬
C = np.dot(A,B) #행렬 곱 수행 

#matrix A, B 형상 출력 => shape
print("A.shape ==",A.shape, ", B.shape ==", B.shape)
print("C.shape ==",C.shape)
print(C)

A.shape == (2, 3) , B.shape == (3, 2)
C.shape == (2, 2)
[[-22 -28]
 [-49 -64]]


###라이브러리 -numpy 행렬 곱 (dot product) 2

- 행렬 곱(dot product)

=> 행렬 곱은, 행렬의 원소 개수가 같아야만 계산할 수 있는 사칙연산의 한계를 벗어난 1.행령곱 조건을 만족하는 다양한 크기의 행렬을 연속으로 만들고 2. 행렬 곱을 연속으로 계산하면서 3. 결과값을 만들 수 있기 때문에 머신러닝과 이미지 프로세싱 분야에서 자주 사용됨 

[예] 입력 행렬 형상이 64×64이고, 결과 행렬 형상이 64×10이라면, 중간에 dot product 를 만족시키는 어떤 형상의 행렬이라도 가질 수 있음. 

행렬 곱을 사용하지 않고 산술연산만 가능하다면, 입력 행렬의 64×64 크기를 가지는 특성 값 만을 사용해야 하기 때문에 다양한 특성을 갖는 필터 개발이 불가능함.

###라이브러리 -numpy broadcast 

-행렬의 사칙연산은 기본적으로 두 개의 행렬 크기가 같은 경우에만 수행할 수 있음. 그러나 numpy 에서는 크기가 다른 두 행렬간에도 사칙연산(+,-,×,/)을 할 수 있는데 이를 브로드캐스트(broadcast)라고 지칭함

=> 차원이 작은 쪽이 큰 쪽의 행 단위로 반복적으로 크기를 맞춘 후에 계산 

In [0]:
A = np.array([[  1,2], [3,4] ]) 
b =5

print(A+b)

[[6 7]
 [8 9]]


In [0]:
C = np.array([ [1,2], [3,4] ]) 
D = np.array([4,5])

print(C+D)


[[5 7]
 [7 9]]


###라이브러리 -numpy 전치행렬 (transpose)

-전치행렬(transpose)

=> 어떤 행렬의 전치행렬(transposed matrix)은 원본 행령의 열은 행으로, 행은 열로 바꾼 것으로서, 원본 행렬을 A라고 하면 전치행렬은 At 로 나타냄.

즉, 1행은 1열로 바꾸고 2행은 2열로, 3행은 3열로 바꾼 행렬을 의미 

In [0]:
A = np.array([[1,2], [3,4], [5,6] ]) # 3×2행렬 

B = A.T  #A의 전치행렬, 2×3 행렬
print("A.shape ==", A.shape, ", B.shape ==", B.shape)
print(A)
print(B)

A.shape == (3, 2) , B.shape == (2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [0]:
# vector 전치행렬 

C =np.array([1,2,3,4,5]) #vector matrix 아님 
D = C.T  #C는 vector 이므로 transpose 않됨

E = C.reshape(1,5)  #1x5 matrix
F = E.T #E의 전치행렬 

print("C.shape ==", C.shape, ", D.shape ==", D.shape)
print("E.shape ==", E.shape, ", F.shape ==", F.shape)
print(F)

C.shape == (5,) , D.shape == (5,)
E.shape == (1, 5) , F.shape == (5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


In [0]:
###라이브러리- numpy 행렬 indexing/slicing

- 행렬 원소 접근 (1)

=> 행렬 원소를 명시적으로(explicit)으로 접근 하기 위해서는 리스트(list)에서처럼, 인덱싱/슬라이싱 모두 사용가능 함. 

In [0]:
A = np.array ([10,20,30,40,50,60]).
reshape(3,2)

print("A.shape ==", A.shape)
print(A)

A.shape == (3, 2)
[[10 20]
 [30 40]
 [50 60]]


[예제 1] A[0,0] 또는 A[0] [0] 은 1행 1열, A[2,1] 또는 A[2] [1] 은 3행 2열임 

In [0]:
print("A[0,0] ==", A[0,0], "A[0][0] ==", A[0][0])
print("A[2,1] ==", A[2,1], "A[2][1] ==", A[2][1])


A[0,0] == 10 A[0][0] == 10
A[2,1] == 60 A[2][1] == 60


[예제2] A [: , 0] 은 모든 행 1열을 나타냄 

[예제 3] A[0:-1, 1:2] 인덱스 0인 1 행부터, 인덱스 -1-1=-2 인 2행까지의 모든 데이터, 그리거 인덱스 1인 2열부터 인덱스 2-1=1 인 2열까지의 모든 데이터 

In [0]:
print("A[0:-1, 1:2] ==", A[0:-1,1:2])

A[0:-1, 1:2] == [[20]
 [40]]


[예제 4] A[ :, : ] 은 모든 행, 모든 열

In [0]:
print("A[ :, 0] ==", A[:, 0])
print("A[ :, :] ==", A[:, :])

A[ :, 0] == [10 30 50]
A[ :, :] == [[10 20]
 [30 40]
 [50 60]]


###라이브러리 -numpy 핼렬 iterator 

-행렬 원소 접근 2

=> 명시적(explicit) 인덱싱/ 슬라이싱 이외에, 행렬 모든 원소를 access 하는 경우에는 iterator 사용 가능 

=> numpy iterator는 C++,Java iterator 처럼 next() 메서드를 통해 데이터 값을 처음부터 끝까지 순차적으로 읽어 들이는 방법을 제공

In [0]:
import numpy as np

A = np.array([ [ 10,20,30,40],[50,60,70,80] ])

print(A, "₩n")
print("A.shape ==", A.shape, "₩n")

#행렬 A 의 iterator 생성 

it = np.nditer(A, flags=['multi_index'], op_flags=['readwrite'])

while not it.finished:
  
  idx = it.multi_index
    
  print("current value => ", A[idx])
  
  it.iternext()

[[10 20 30 40]
 [50 60 70 80]] ₩n
A.shape == (2, 4) ₩n
current value =>  10
current value =>  20
current value =>  30
current value =>  40
current value =>  50
current value =>  60
current value =>  70
current value =>  80
