<a href="https://colab.research.google.com/github/zza0818/py-11/blob/master/ann/DL1_Neuron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[link:DeepLearningFastStart](https://github.com/alfredessa/DeepLearningFastStart/blob/master/DL-Neuron.ipynb)

In [0]:
from IPython.core.display import HTML, Image
css_file = 'style.css'
HTML(open(css_file, 'r').read())

>[Deep Learning Fast Start](#scrollTo=rpOz6FctZksc)

>>[The Neuron](#scrollTo=rpOz6FctZksc)

>[Neuron: Learning Objectives](#scrollTo=AdYUbt7NZksh)

>[What is a Neuron?](#scrollTo=VyrTxpNgZksr)

>[Neuron Structure](#scrollTo=E7F0cR8wZksv)

>[Neuron's Two Step Computation](#scrollTo=x2OLc0TjZktA)

>[Neuron Computation (Step 1)](#scrollTo=fQXjX_SGZktb)

>[Neuron Computation Example (Step 1)](#scrollTo=QsFRvAmzZktO)

>[Code for Neuron Computation (Step 1): 선형합](#scrollTo=Vz7wIWsvZktq)

>>>[Using For Loop](#scrollTo=DfYosU--Zktr)

>>>[Using List Comprehension](#scrollTo=3CRFr95xZkt9)

>>>[Using Numpy Dot Product](#scrollTo=WbQEmj4RZkuH)

>[Neuron Computation (Step 2): 비선형 활동](#scrollTo=bsM3Lj8kZkuS)

>[Activation Function Examples](#scrollTo=OLNNuCKaZkuX)

>[Computation Example (Step 2)](#scrollTo=lq_CD75oZkuf)

>[Code for Neuron Activation (Step 2)](#scrollTo=UnDed5j5Zkuj)

>>>[스텝 함수 (Heaviside function)](#scrollTo=S8d3xeTXZkuk)

>>>[ReLU 함수 (Rectified Linear Unit function)](#scrollTo=-JvsHNIKZkuq)

>>>[Sigmoid 함수](#scrollTo=0ewW3Bf2Zkuu)

>[Data Structures for Neuron Computation](#scrollTo=dFL_PpKcZku0)

>[Neuron Class](#scrollTo=IrCEDxj0ZkvF)

>>>[Define Activation Functions](#scrollTo=XsuyR0uVZkvM)

>>>[Define Neuron Class](#scrollTo=-6iSXoGXZkvS)

>>>[Create Neuron Object and Compute](#scrollTo=xKkWvT0WZkvX)

>>>[선형합(transfer)](#scrollTo=Cyjcmq68Zkv0)

>>>[Activating neuron](#scrollTo=Ai5ejhUYZkv8)

>>>[뉴런의 기본 활동 윈리가 이해됩니까?](#scrollTo=PIqhE_UaZkwP)

>>>[[도전 과제]  100 개의 입력에 대한 뉴런의 출력을 세 가지 방식으로 구하시오.](#scrollTo=BSoP0vwBZkwR)

>[Great! Welcome to the World of Perceptron.](#scrollTo=LzTllMcCZkw1)



# Deep Learning Fast Start

## The Neuron


<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Deep Learning Fast Start</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="http://alfredessa.com" property="cc:attributionName" rel="cc:attributionURL">Alfred Essa</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

# 1. Neuron: Learning Objectives

**1:** Understand the basic *concept* of an artificial neuron or perceptron

> [perceptron(퍼셉트론 개념)](http://blog.naver.com/samsjang/220948258166)

**2:** Describe a neuron's two-step *computation* process
> 뉴런은 입력값에 두 단계로 계산을 수행하여서 출력값으로 변환한다.

>> 1단계 : 들어오는 것들을 더하고 가중치를 더해준다

>> 2단계 : 비선형함수로 바꿔준다

**3:** Recognize the *parameters* of a neuron
> 뉴런의 파라미터는 가중치(weight)와 바이어스(bias)로 구성된다.

**4:** Understand how a single neuron can implement linear or logistic regression

**5:** Write code, in the form of crude *Python class*, which implements a neuron's computation


# 2.  What is a Neuron?

> **Definition**: A neuron is the *atomic computational unit* of an **artificial neural network** (ANN).

 # 3. Neuron Structure

<img src="https://github.com/alfredessa/DeepLearningFastStart/raw/2642623f099ad676de05b0936700130387149432/images/bioneuron.png" style="width: 50%; height: 50%" />

- In a biological neuron input signals come in through dendrites
> dendrites: 가지돌기

>> 가지돌기 마다 [연결되어있는 강도]가 다르다 → 가중치

- The signals are processed in the nucleus

- The output signal is transmitted to other neurons through the axon
>axon: 축삭돌기 
>> 다른 뉴런한테 다른 정보를 전달(activation) → 비선형활동을 하면서!

- 생물학적인 뉴런은 덴드라이트들(dendrites)로부터 받은 입력 신호(이온 흐름)를 처리한 후 일정 기준이 만족되면 액손(axon)을 통해 다른 뉴런에게 신호(정보)를 전달한다. 
> McCulloch-Pitts neuron (MCP neuron)

- 생물학적인 뉴런의 정보 처리 구조를 수학적으로 도식화하면 다음과 같다. ( 입력정보를 출력정보로 변환 )
> 퍼셉트론(perceptron) 학습 규칙

<img src="https://github.com/alfredessa/DeepLearningFastStart/raw/2642623f099ad676de05b0936700130387149432/images/function.png" style="width: 50%; height: 50%" />

여러가지 input의 가중치가 다름 f에서 더하기 고유한 bias 더해줌 비선형 성질 값을 y로 출력(2단계)

- A neuron can be viewed as a mathematical function

- A neuron accepts a set of inputs, performs a computation on that input, and returns an output

- 뉴런은 주위의 다른 뉴런들로부터 여러 입력을 받아 내부(핵)에서 처리한 후 일정 조건이 되면 다른 뉴런에게 처리된 결과를 전송한다. 

# 4. Neuron's Two Step Computation

<img src="https://github.com/alfredessa/DeepLearningFastStart/raw/2642623f099ad676de05b0936700130387149432/images/twostep.png" style="width: 60%; height: 60%" />

- A neuron performs its computation in two-steps (뉴런 내에서의 처리는 두 단계로 구성된다.) 

> 1단계 : 선형 (합)

> 2단계 : 비선형 (활동)

- During step 1 a linear function operates on the inputs on the inputs: $x_{1}..x_{n}$ and produces an output $z$. --> 선형 합 (transfer)

- During step 2 a non-linear function, called the activation function, performs a computation on the input $z$ to produce the final output $y$.  --> 비선형 활동(activation)

<img src="https://github.com/alfredessa/DeepLearningFastStart/raw/2642623f099ad676de05b0936700130387149432/images/twostep2.png" style="width: 60%; height: 60%" />

                                                                            ▲ Perceprtron 구조

- We will represent the first function, sometimes called the transfer function, with the symbol $\Sigma$. -> 선형합(transfer)

- We will represent the second function, called the activation function, with the symbol $\phi$ -> 비선형 활동(activation)

# 5. Neuron Computation (Step 1) - 선형 합

<img src="https://github.com/alfredessa/DeepLearningFastStart/raw/2642623f099ad676de05b0936700130387149432/images/transferfunction.png" style="width: 75%; height: 75%">

- Each neuron accepts $n$ inputs.

- A "weight" is associated with each input: $x_{n} \mapsto w_{n}$
> 가중치는 각각의 입력에 할당된다.

- Then a "bias" term $b$ is added to the weighted sum of inputs.
> 가중치가 뱐영된 입력합에 바이어스(상수값)이 더해진다.

# 6. Neuron Computation Example (Step 1)

<img src="https://github.com/alfredessa/DeepLearningFastStart/raw/2642623f099ad676de05b0936700130387149432/images/transferexample.png" style="width: 60%; height: 60%" >

3개의 입력이 있을 때
가중치 3.2 하고 더하기 - 을 해주게 되면 첫번째 단계에서 뉴런이 얻은 값이 1.06임

- We have three inputs for this neuron, with values: $[2.3,4.5,1.3]$

- A "weight" is associated with each input: $[3.2, -1.9, 2.5]$. We also have a value for the bias: $-1$

- 각 입력값은 가중치(weight)를 곱한 후 합산한 후, 상수값(bias)가 더해져서 처리된다.

- The weighted sum plus the bias is $z = 1.06$

# 7. Code for Neuron Computation (Step 1): 선형합
> 세 가지 방법으로 뉴런을 정의

> 선형합(transfer) 기능 설계

### Using For Loop

In [0]:
# 위의 그림의 예를 예시로 든다

In [0]:
# 우리가 테스트하려는 뉴런의 현재 상태를 나타냄
inputs = [2.3,4.5,1.3] 
weights = [3.2,-1.9,2.5] # 가중치
bias = -1

# input* weighs +bias

In [0]:
def neuron1(x,w,b):
    z=0 # 선형 합을 계산하는 출력 값
    for x_,w_ in zip(x,w): # 입력값과 가중치는 같은 차원이기 때문에 zip() 함수 사용
        z += x_ * w_
    z+=b
    return z

In [0]:
neuron1(inputs,weights,bias)

1.0600000000000005

### Using List Comprehension - 리스트 내포

In [0]:
# nueron1과 같은 함수

def neuron2(x,w,b):
    z = sum([x_*w_ for x_,w_ in zip(x,w)]) + b 
    return z

In [0]:
neuron2(inputs,weights,bias)

1.0600000000000005

### Using Numpy Dot Product

In [0]:
# 제일 많이 이용하는 방식

import numpy as np
def neuron3(x,w,b):
    z = np.dot(w,x) + b # dot 함수 가중치와 x를 곱해준다 그러고나서 상수값을 더해준다 # numpy의 dot 함수 → 곱해준다
    return z # 더한값을 리턴해준다

In [0]:
neuron3(inputs,weights,bias)

1.0600000000000005

# 8. Neuron Computation (Step 2): 비선형 활동

<img src="https://github.com/alfredessa/DeepLearningFastStart/raw/2642623f099ad676de05b0936700130387149432/images/twostep2.png" style="width: 60%; height: 60%">|

# 9. Activation Function Examples 
> 비선형 함수 : activation 함수

<img src="https://github.com/alfredessa/DeepLearningFastStart/raw/2642623f099ad676de05b0936700130387149432/images/stepfunction.png" style="width: 60%; height: 60%">

▲ 어떤 값을 초과하면 값을 전달해주고, 초과하지 않으면 값을 전달해주지 않고 기다린다 
> 모 아니면 도 

> 극과극

<img src="https://github.com/alfredessa/DeepLearningFastStart/raw/2642623f099ad676de05b0936700130387149432/images/relufunction.png" style="width: 60%; height: 60%">

▲ 0과 값의 최대치를 구해줌 

<img src="https://github.com/alfredessa/DeepLearningFastStart/raw/2642623f099ad676de05b0936700130387149432/images/sigmoidfunction.png" style="width: 60%; height: 60%">

▲ 0.5-1 사이의 값이 나옴

# Computation Example (Step 2)

<img src="https://github.com/alfredessa/DeepLearningFastStart/raw/2642623f099ad676de05b0936700130387149432/images/activationexample.png" style="width: 60%; height: 60%">

# Code for Neuron Activation (Step 2)
> 세 가지 함수로 뉴런의 활동을 정의

### 스텝 함수 (Heaviside function)
> 0 or 1

In [0]:
def heaviside(z): # 스칼라 n by 1 에레이가 되면 문제가 발생
#   if x<0:
#      return 0
#    else
#    return 1
     return np.heaviside(z, 0)  # threshold = 0

### ReLU 함수 (Rectified Linear Unit function)
> 0 or positive number

In [0]:
def relu(z):
    return np.maximum(0,z)

### Sigmoid 함수

> $-\infty \lt z \lt \infty$ 범위를 0 ~ 1 범위로 근사.

In [0]:
def sigmoid(z):
        return 1.0/(1.0+np.exp(-z))
  
  # 아주 넓은 범위의 값을 smooth 하게 더 처리해줌
  # 생체 신호가 어떤 값을 인지하지 못한다면 안된다

<img src="https://t1.daumcdn.net/cfile/tistory/275BAD4F577B669920" style="width: 60%; height: 60%">

> https://t1.daumcdn.net/cfile/tistory/275BAD4F577B669920

***

# 10. Data Structures for Neuron Computation

- We represent the input $\mathbf{x}$ as a column vector. $\mathbf{x} =\begin{bmatrix}
    x_1\\
    x_2\\
    \vdots \\
    x_n
\end{bmatrix}$

- We represent the weights $\mathbf{w}$ as a column vector but take it's transform to obtain a row vector $\mathbf{w}^\top = \begin{bmatrix}
    w_1\
    w_2\
    \dots \
    w_n
    \end{bmatrix}$

- We represent the bias $\mathbf{b}$ as a scalar $b$.

- The result of the transfer function computation:  $z = \mathbf{w}^\top \mathbf{x} + b$

- The result of the activation function computation: $a$ = $\phi(z)$

$$ z = \begin{bmatrix}
    x_1\\
    x_2\\
    \vdots \\
    x_n
\end{bmatrix} 
\begin{bmatrix}
    w_1\
    w_2\
    \dots \
    w_n
    \end{bmatrix} + b$$

$$z = \mathbf{w}^\top \mathbf{x} + b$$

# 11. Neuron Class 

In [0]:
import numpy as np

# 하나의 뉴런에 대해서는 bias가 한개이지만
# 여러개의 뉴런에 대해서는 bias도 여러개임
# 배열로 정의해주어야 함

### Define Activation Functions(3개의 비선형 함수)

In [0]:
# nonlinear activation function
def relu(z):
    return np.maximum(0,z)

def sigmoid(z):
    return 1.0/(1.0+np.exp(-z))
    
def heaviside(z):
#     if z<0:
#         return 0
#     else:
#         return 1
    return np.heaviside(z,0) # threshold = 0

### Define Neuron Class

In [0]:
class Neuron(object): # 하나의 뉴런에 대한 함수
    
    # size = size or number of inputs
    def __init__(self,size): # 사이즈는 몇개의 input이 들어오는지 = 가중치 개수
        self.weights = np.random.randn(size) # 가중치 무작위
        self.bias = np.random.randn() # 뮤적유ㅏ
        
    # computes z = weighted sum + bias
    def y_hat(self,x,phi): # 선형으로 나온 ouput 값을 계산
        z = np.dot(self.weights,x) + self.bias  # transfer
        a = phi(z) # activation # phi = activation 함수
        return(a)  # output
    
    
    # updates weights and biases
    def update_params(self,weights,bias):
        self.weights = np.array([weights])
        self.bias = np.array([bias])
        
        # parameter가 몇일 때 가장 이상적인가? -> 머신러닝으로 해결!

### Create Neuron Object and Compute

In [0]:
# Set a seed for random number generation
np.random.seed(0)

In [0]:
N1 = Neuron(3)  # input size = 3 # 들어오는 input이 3개
N1

In [0]:
N1.weights,N1.bias

(array([1.76405235, 0.40015721, 0.97873798]), 2.240893199201458)

In [0]:
N1a=Neuron(3)
N1a.weights

# 위의 코드랑 다르다! seed값이 달라져서!
# 돌릴수록 달라져

array([ 1.49407907, -0.20515826,  0.3130677 ])



---



### Neuron 
> Make another neuron with different parameters

In [0]:
# 원하는 뉴런이 있다면 직접 정의 → update_params 사용
# Set new weights and bias
# Make another neuron with different parameters
weights = [3.2,-1.9,2.5]
bias = -1

In [0]:
N1.update_params(weights,bias)

In [0]:
N1.weights,N1.bias # 내가 정의한걸로 바뀌었다

(array([[ 3.2, -1.9,  2.5]]), array([-1]))

### 선형합(transfer)

In [0]:
# input
x = [2.3,4.5,1.3]  # 입력

In [0]:
np.dot(N1.weights,x) + N1.bias

array([1.06])

### Activating neuron

In [0]:
N1.y_hat(x,heaviside)

array([1.])

In [0]:
N1.y_hat(x,relu)

array([1.06])

In [0]:
N1.y_hat(x,sigmoid)

array([0.74269055])

### 뉴런의 기본 활동 윈리가 이해됩니까? 넹!

***

### [도전 과제]  100 개의 입력에 대한 뉴런의 출력을 세 가지 방식으로 구하시오.

> 세 가지 활동 함수 이용 : heaviside(), relu(), sigmoid()

In [0]:
# Set a seed for random number generation
np.random.seed(0) # 교수님과 같은 코드로 하기 위해서 seed 함수로 통일하여야 함

In [0]:
N100 = Neuron(100) # size 100

In [0]:
N100.weights,N100.bias

(array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
        -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ,
         0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323,
         0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574,
        -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502,  2.26975462,
        -1.45436567,  0.04575852, -0.18718385,  1.53277921,  1.46935877,
         0.15494743,  0.37816252, -0.88778575, -1.98079647, -0.34791215,
         0.15634897,  1.23029068,  1.20237985, -0.38732682, -0.30230275,
        -1.04855297, -1.42001794, -1.70627019,  1.9507754 , -0.50965218,
        -0.4380743 , -1.25279536,  0.77749036, -1.61389785, -0.21274028,
        -0.89546656,  0.3869025 , -0.51080514, -1.18063218, -0.02818223,
         0.42833187,  0.06651722,  0.3024719 , -0.63432209, -0.36274117,
        -0.67246045, -0.35955316, -0.81314628, -1.7262826 ,  0.17742614,
        -0.40178094, -1.63019835,  0.46278226, -0.9

In [0]:
N100.weights.shape

(100,)

In [0]:
# input(입력)
x100 = np.random.randn(100) # input
x100.shape,x100

((100,),
 array([-1.34775906, -1.270485  ,  0.96939671, -1.17312341,  1.94362119,
        -0.41361898, -0.74745481,  1.92294203,  1.48051479,  1.86755896,
         0.90604466, -0.86122569,  1.91006495, -0.26800337,  0.8024564 ,
         0.94725197, -0.15501009,  0.61407937,  0.92220667,  0.37642553,
        -1.09940079,  0.29823817,  1.3263859 , -0.69456786, -0.14963454,
        -0.43515355,  1.84926373,  0.67229476,  0.40746184, -0.76991607,
         0.53924919, -0.67433266,  0.03183056, -0.63584608,  0.67643329,
         0.57659082, -0.20829876,  0.39600671, -1.09306151, -1.49125759,
         0.4393917 ,  0.1666735 ,  0.63503144,  2.38314477,  0.94447949,
        -0.91282223,  1.11701629, -1.31590741, -0.4615846 , -0.06824161,
         1.71334272, -0.74475482, -0.82643854, -0.09845252, -0.66347829,
         1.12663592, -1.07993151, -1.14746865, -0.43782004, -0.49803245,
         1.92953205,  0.94942081,  0.08755124, -1.22543552,  0.84436298,
        -1.00021535, -1.5447711 ,  1.18802

In [0]:
# transfer: weighted linear sum + bias
np.dot(N100.weights,x100) + N100.bias

10.886612705858221

In [0]:
N100.y_hat(x100,heaviside) # 0보다 크므로 1 반환

1.0

In [0]:
N100.y_hat(x100,relu)

10.886612705858221

In [0]:
N100.y_hat(x100,sigmoid)

0.9999812933486968

***

# Great! Welcome to the World of Perceptron.